name: 'Setup Node.js and Dependencies'
description: 'Set up Node.js, npm, and install dependencies with caching'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      shell: bash
      run: npm ci