name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      repository-projects: write
      deployments: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup

      # Ensure npm >= 11.5.1 (required for OIDC Trusted Publishing)
      - name: Upgrade npm for OIDC
        run: npm i -g npm@^11.5.1

      # Make sure we're pointed at the public npm registry (no .npmrc auth here)
      - run: npm config set registry https://registry.npmjs.org

      - name: Build
        run: npm run build

      - name: PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}